# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKjyMAPZMbL6Szd--PFf6QJRHrxRc4hq
"""

with open('/content/project1.md', 'w') as f:
  f.write('') # Create an empty file

with open('/content/project1.md', 'r') as f:
  project_md_content = f.read()
print(project_md_content)

import yfinance as yf
import pandas as pd

ts_ticker = '2330.TW'

# 下載台積電過去一年的歷史數據
ts_data = yf.download(ts_ticker, period='1y')

# 顯示數據的前幾行
display(ts_data.head())

import matplotlib.pyplot as plt

# 計算移動平均線
ts_data['MA5'] = ts_data[('Close', ts_ticker)].rolling(window=5).mean()
ts_data['MA20'] = ts_data[('Close', ts_ticker)].rolling(window=20).mean()

# 繪製股價走勢圖
plt.figure(figsize=(14, 7))
plt.plot(ts_data.index, ts_data[('Close', ts_ticker)], label='Close Price', color='blue')
plt.plot(ts_data.index, ts_data['MA5'], label='5-Day Moving Average', color='red')
plt.plot(ts_data.index, ts_data['MA20'], label='20-Day Moving Average', color='green')

# 添加圖表標題和標籤
plt.title('TSMC (2330.TW) Stock Price Trend and Moving Averages (Past Year)')
plt.xlabel('Date')
plt.ylabel('Price (NTD)')
plt.legend()
plt.grid(True)
plt.show()

# 檢查 DataFrame 的總行數
print(f"DataFrame 的總行數: {len(ts_data)}")

# 檢查 'MA5' 和 'MA20' 列的非空值數量
print(f"'MA5' 列的非空值數量: {ts_data['MA5'].count()}")
print(f"'MA20' 列的非空值數量: {ts_data['MA20'].count()}")

# 顯示 'MA5' 和 'MA20' 列的前25個值，以確認 NaN 的情況
display(ts_data[['MA5', 'MA20']].head(25))