# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H4eP5wk1Zy-UdYbMi0imyPJyN5-pXF9t
"""

a=1

type(a)

print(a)

b='abc'

type(b)

print(b)

c=input("請輸入變數c")

type(c)

print(c)

rooms = {1: 'Foyer', 2: 'Conference Room'}

type(rooms)

print(rooms[2])

rooms = {'1': 'Foyer', '2': 'Conference Room'}

rooms['1']

rooms = {1: 'Foyer', 2: 'Conference Room'}

room = int(input('Enter the room number: '))

room

rooms[int(room)]

