# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHl_7zPxZ_QKi0QB3njyRpay8JFsDlxw
"""

list_1 = [1,2]
list_2 = [3,4]
list_3 = list_1 + list_2
list_4 = list_3 * 3
print(list_4)

list_3

list_4